name: news_app_api
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.6
  url_launcher_web: ^2.0.7
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png